[package]
name = "dmdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmdb-sys = { path = "../dmdb-sys" }

thiserror = "1"

[features]
default = []
bundled = ["dmdb-sys/bundled"]
